package com.skillbridge.ai.service;

import com.skillbridge.ai.RoadmapProducer;
import com.skillbridge.ai.model.Roadmap;
import com.skillbridge.ai.repository.RoadmapRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class SkillGapService {

    @Value("${groq.api.key}")
    private String groqApiKey;

    @Value("${groq.api.url}")
    private String groqApiUrl;

    @Value("${groq.model}")
    private String groqModel;

    private final RoadmapRepository roadmapRepository;
    private final RestTemplate restTemplate;
    private final RoadmapProducer roadmapProducer;

    public Roadmap generateRoadmap(String userEmail, String currentSkills, String targetRole) {

        String prompt = String.format("""
You are an expert career coach. Create a highly structured, beginner-friendly learning roadmap.

Target Role: %s
Current Skills: %s

Generate the roadmap in this EXACT structure. Do not skip any section. Use plain text only, no markdown symbols like ** or ##.

---
SKILL GAP ANALYSIS

What you already know:
- List the relevant skills from current skills

What you need to learn:
- List 4 to 6 missing skills needed for the target role

---
MONTH 1 - FOUNDATION

Goal: [One line goal for this month]

Week 1:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 2:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 3:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 4:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Month 1 Milestone: [What you should be able to do by end of month 1]

---
MONTH 2 - INTERMEDIATE

Goal: [One line goal for this month]

Week 1:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 2:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 3:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 4:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Month 2 Milestone: [What you should be able to do by end of month 2]

---
MONTH 3 - ADVANCED AND PROJECTS

Goal: [One line goal for this month]

Week 1:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 2:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 3:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Week 4:
  Topics: [What to study]
  Resources: [Free YouTube channels or documentation links]
  Practice: [What to build or practice]

Month 3 Milestone: [What you should be able to do by end of month 3]

---
JOB ROLES YOU CAN APPLY FOR
- [Role 1]
- [Role 2]
- [Role 3]

PLATFORMS TO APPLY
- LinkedIn
- Indeed
- Naukri (for India)
- Internshala (for freshers)
- Wellfound (for startups)
- Remote.co (for remote jobs)
---

Keep the language simple and easy to understand. Be specific with topics and resource names.
""", targetRole, currentSkills);

        String aiResponse = callGroqAPI(prompt);

        Roadmap roadmap = new Roadmap();
        roadmap.setUserEmail(userEmail);
        roadmap.setCurrentSkills(currentSkills);
        roadmap.setTargetRole(targetRole);
        roadmap.setSkillGap("Generated by AI");
        roadmap.setRoadmapContent(aiResponse);

        Roadmap saved = roadmapRepository.save(roadmap);
        roadmapProducer.sendRoadmapEmail(userEmail, aiResponse);

        return saved;
    }

    private String callGroqAPI(String prompt) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(groqApiKey);

        Map<String, Object> requestBody = Map.of(
                "model", groqModel,
                "messages", List.of(
                        Map.of("role", "user", "content", prompt)
                ),
                "max_tokens", 2000
        );

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

        ResponseEntity<Map> response = restTemplate.postForEntity(
                groqApiUrl, request, Map.class
        );

        Map<String, Object> responseBody = response.getBody();
        List<Map<String, Object>> choices = (List<Map<String, Object>>) responseBody.get("choices");
        Map<String, Object> message = (Map<String, Object>) choices.get(0).get("message");

        return (String) message.get("content");
    }

    public List<Roadmap> getRoadmapsByEmail(String email) {
        return roadmapRepository.findByUserEmail(email);
    }
}